version: '3.8'

services:
  memebucket:
    platform: linux/amd64
    image: ghcr.io/rustedaperture/memebucket:master
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
