version: '3.8'

services:
  ezgif:
    image: ghcr.io/rustedaperture/ezgif:master
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
